version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    env_file:
      - .env.db
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: